"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import {
  QueryClient,
  QueryClientProvider,
} from 'react-query'
import { Provider } from "react-redux";
import store from "@/redux/stre";

const queryClient = new QueryClient()

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}> 
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
        <Toaster />
    </html>
      </QueryClientProvider>
    </Provider>
  );
}
