import { Poppins } from "next/font/google";
import "./globals.css";
import NoSsr from "./utils/NoSsr";
import MainProvider from "./utils/MainProvider";
import Link from "next/link";

const inter = Poppins({ subsets: ["latin"],
style: ["normal"],
weight:["100","300","400","500","700","900"] });

export const metadata = {
  title: "Fame Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <head></head>
      {/* <Link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
      <body className={inter.className} suppressHydrationWarning >
      <NoSsr>
        <MainProvider>
        {children}
        </MainProvider>
      </NoSsr>
      {/* <footer className="p-1 sidebarBg text-white">
<p className="text-xs text-center">Design & Developed By Fame Business Solutions</p>
      </footer> */}
        </body>
    </html>
  
  );
}
